# For more information see: https://github.com/mikepenz/gradle-dependency-submission

name: Update dependency graph

on:
  push:
    branches: [ "master" ]

permissions:
  # Write permission required by gradle-dependency-submission
  contents: write

jobs:
  submit-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Submit Gradle dependencies
        uses: mikepenz/gradle-dependency-submission@v0.7.1
        with:
          use-gradlew: false
          gradle-build-configuration: compileClasspath
